"""
Prometheus metrics for monitoring.

Tracks request counts, latency, cache hits, retrieval quality, etc.
All metrics follow Prometheus naming conventions (snake_case with _total, _duration_seconds suffix).
"""

from prometheus_client import Counter, Histogram, Gauge


# Request metrics
REQUESTS = Counter(
    "rag_requests_total",
    "Total RAG requests",
    labelnames=["status"],  # cache_hit, success, blocked, error
)

LATENCY = Histogram(
    "rag_request_duration_seconds",
    "RAG request latency in seconds",
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0),
)

# Retrieval metrics
RETRIEVAL_LATENCY = Histogram(
    "rag_retrieval_duration_seconds",
    "Retrieval step latency in seconds",
    labelnames=["retriever_type"],  # dense, bm25, hybrid
)

CHUNKS_RETRIEVED = Histogram(
    "rag_chunks_retrieved",
    "Number of chunks retrieved",
    labelnames=["retriever_type"],
)

# Generation metrics
GENERATION_LATENCY = Histogram(
    "rag_generation_duration_seconds",
    "LLM generation latency in seconds",
)

TOKENS_GENERATED = Counter(
    "rag_tokens_generated_total",
    "Total tokens generated by LLM",
)

# Cache metrics
CACHE_HITS = Counter(
    "rag_cache_hits_total",
    "Cache hit count",
)

CACHE_MISSES = Counter(
    "rag_cache_misses_total",
    "Cache miss count",
)

# Vector store metrics
DOCUMENTS_INDEXED = Gauge(
    "rag_documents_indexed_total",
    "Total documents in vector store",
)

CHUNKS_INDEXED = Gauge(
    "rag_chunks_indexed_total",
    "Total chunks in vector store",
)
